// resources/js/components/dashboard/DataTable.vue
<script setup lang="ts">
interface Column {
    key: string;
    label: string;
    format?: 'currency' | 'date' | 'badge' | 'text';
    badgeColors?: Record<string, string>;
}

interface Props {
    title: string;
    columns: Column[];
    data: any[];
    emptyMessage?: string;
    badge?: {
        text: string;
        color: string;
        count?: number;
    };
}

const props = withDefaults(defineProps<Props>(), {
    emptyMessage: 'No hay datos disponibles'
});

const formatValue = (value: any, format?: string, badgeColors?: Record<string, string>) => {
    if (!value && value !== 0) return '-';

    switch (format) {
        case 'currency':
            return new Intl.NumberFormat('es-CO', {
                style: 'currency',
                currency: 'COP',
                minimumFractionDigits: 0
            }).format(value);
        case 'date':
            return new Date(value).toLocaleDateString('es-CO');
        case 'badge':
            return { value, color: badgeColors?.[value] || 'bg-gray-100 text-gray-800' };
        default:
            return value;
    }
};

const getBadgeClass = (value: string, badgeColors?: Record<string, string>) => {
    const defaultColors: Record<string, string> = {
        'completada': 'bg-green-100 text-green-800',
        'pendiente': 'bg-yellow-100 text-yellow-800',
        'cancelada': 'bg-red-100 text-red-800',
        'resuelto': 'bg-green-100 text-green-800',
        'activo': 'bg-blue-100 text-blue-800',
        'inactivo': 'bg-gray-100 text-gray-800'
    };

    return badgeColors?.[value] || defaultColors[value] || 'bg-gray-100 text-gray-800';
};
</script>

<template>
    <div
        class="bg-white dark:bg-gray-800 overflow-hidden shadow rounded-lg border border-gray-200 dark:border-gray-700">
        <div class="px-4 py-5 sm:p-6">
            <div class="flex items-center justify-between mb-4">
                <h3 class="text-lg leading-6 font-medium text-gray-900 dark:text-gray-100">{{ title }}</h3>
                <span v-if="badge" :class="badge.color"
                    class="inline-flex px-2 py-1 text-xs font-semibold rounded-full">
                    {{ badge.text }}
                    <span v-if="badge.count !== undefined" class="ml-1">{{ badge.count }}</span>
                </span>
            </div>

            <div class="overflow-hidden">
                <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                    <thead class="bg-gray-50 dark:bg-gray-700">
                        <tr>
                            <th v-for="column in columns" :key="column.key"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                                {{ column.label }}
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                        <tr v-for="(item, index) in data" :key="index"
                            class="hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors">
                            <td v-for="column in columns" :key="column.key" class="px-6 py-4 whitespace-nowrap text-sm">
                                <template v-if="column.format === 'badge'">
                                    <span :class="getBadgeClass(item[column.key], column.badgeColors)"
                                        class="inline-flex px-2 py-1 text-xs font-semibold rounded-full">
                                        {{ item[column.key].charAt(0).toUpperCase() + item[column.key].slice(1) }}
                                    </span>
                                </template>
                                <template v-else-if="column.format === 'currency'">
                                    <span class="font-medium text-gray-900 dark:text-gray-100">{{
                                        formatValue(item[column.key], column.format) }}</span>
                                </template>
                                <template v-else>
                                    <span
                                        :class="column.format === 'date' ? 'text-gray-900 dark:text-gray-100' : 'text-gray-600 dark:text-gray-300'">
                                        {{ formatValue(item[column.key], column.format) }}
                                    </span>
                                </template>
                            </td>
                        </tr>
                        <tr v-if="data.length === 0">
                            <td :colspan="columns.length"
                                class="px-6 py-8 text-center text-sm text-gray-500 dark:text-gray-400">
                                <div class="flex flex-col items-center">
                                    <svg class="w-12 h-12 text-gray-300 dark:text-gray-600 mb-2" fill="none"
                                        stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z">
                                        </path>
                                    </svg>
                                    {{ emptyMessage }}
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</template>

// resources/js/components/DataTable/DataTable.tsx
import { useAppMode } from '@/contexts/AppModeContext';
import { Link } from '@inertiajs/react';

interface Column {
    key: string;
    label: string;
    render?: (value: unknown, item: unknown) => React.ReactNode;
    className?: string;
}

interface Action {
    type: 'view' | 'edit' | 'delete' | 'toggle' | 'custom';
    href?: string;
    onClick?: (item: Record<string, unknown>) => void;
    icon: string;
    title: string;
    className?: string;
    condition?: (item: Record<string, unknown>) => boolean;
}

interface DataTableProps {
    data: Record<string, unknown>[];
    columns: Column[];
    actions: Action[];
    emptyState: {
        icon: string;
        title: string;
        description: string;
        showAddButton?: boolean;
        addButtonText?: string;
        addButtonHref?: string;
    };
    getItemKey: (item: Record<string, unknown>) => string | number;
}

export default function DataTable({ data, columns, actions, emptyState, getItemKey }: DataTableProps) {
    const { settings } = useAppMode();

    const getModeClasses = () => {
        switch (settings.ageMode) {
            case 'niños':
                return 'font-comic text-adaptive-kids';
            case 'jóvenes':
                return 'font-modern text-adaptive-teen';
            default:
                return 'font-classic text-adaptive-adult';
        }
    };

    const renderCellValue = (column: Column, item: Record<string, unknown>) => {
        if (column.render) {
            return column.render(item[column.key], item);
        }
        const value = item[column.key];
        return value !== undefined && value !== null ? value : '-';
    };

    const renderAction = (action: Action, item: Record<string, unknown>, index: number) => {
        // Verificar condición si existe
        if (action.condition && !action.condition(item)) {
            return null;
        }

        const baseClasses = action.className || 'text-blue-600 hover:text-blue-900 dark:text-blue-400 dark:hover:text-blue-300';

        if (action.type === 'view') {
            return (
                <Link key={index} href={action.href?.replace(':id', String(item.id)) || ''} className={baseClasses} title={action.title}>
                    {action.icon}
                </Link>
            );
        }

        if (action.type === 'edit') {
            return (
                <Link key={index} href={action.href?.replace(':id', String(item.id)) || ''} className={baseClasses} title={action.title}>
                    {action.icon}
                </Link>
            );
        }

        if (action.type === 'delete' || action.type === 'toggle' || action.type === 'custom') {
            return (
                <button key={index} onClick={() => action.onClick?.(item)} className={baseClasses} title={action.title}>
                    {action.icon}
                </button>
            );
        }

        return null;
    };

    if (data.length === 0) {
        return (
            <div className="overflow-hidden rounded-lg bg-white shadow dark:bg-gray-800">
                <div className="p-12 text-center">
                    <div className="mb-4 text-6xl">{emptyState.icon}</div>
                    <h3 className={`mb-2 text-lg font-medium text-gray-900 dark:text-gray-100 ${getModeClasses()}`}>{emptyState.title}</h3>
                    <p className={`mb-4 text-gray-600 dark:text-gray-400 ${getModeClasses()}`}>{emptyState.description}</p>
                    {emptyState.showAddButton && emptyState.addButtonHref && (
                        <Link
                            href={emptyState.addButtonHref}
                            className={`inline-flex items-center rounded-lg bg-blue-600 px-4 py-2 font-medium text-white transition-colors hover:bg-blue-700 ${getModeClasses()}`}
                        >
                            {emptyState.addButtonText}
                        </Link>
                    )}
                </div>
            </div>
        );
    }

    return (
        <div className="overflow-hidden rounded-lg bg-white shadow dark:bg-gray-800">
            <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                    <thead className="bg-gray-50 dark:bg-gray-900">
                        <tr>
                            {columns.map((column) => (
                                <th
                                    key={column.key}
                                    className={`px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase dark:text-gray-400 ${getModeClasses()} ${column.className || ''}`}
                                >
                                    {column.label}
                                </th>
                            ))}
                            {actions.length > 0 && (
                                <th
                                    className={`px-6 py-3 text-right text-xs font-medium tracking-wider text-gray-500 uppercase dark:text-gray-400 ${getModeClasses()}`}
                                >
                                    Acciones
                                </th>
                            )}
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200 bg-white dark:divide-gray-700 dark:bg-gray-800">
                        {data.map((item) => (
                            <tr key={getItemKey(item)} className="hover:bg-gray-50 dark:hover:bg-gray-700">
                                {columns.map((column) => (
                                    <td key={column.key} className={`px-6 py-4 whitespace-nowrap ${getModeClasses()} ${column.className || ''}`}>
                                        {renderCellValue(column, item)}
                                    </td>
                                ))}
                                {actions.length > 0 && (
                                    <td className={`px-6 py-4 text-right text-sm font-medium whitespace-nowrap ${getModeClasses()}`}>
                                        <div className="flex justify-end space-x-2">
                                            {actions.map((action, index) => renderAction(action, item, index))}
                                        </div>
                                    </td>
                                )}
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
